# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4a6a396591c2f8f83511ab1904461c6d"
name = "ICTECHGiftCard"
application_url = "https://gathering-advanced-multi-implies.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
uri = "/webhooks/compliance"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = [ "app/scopes_update" ]
uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_products,read_gift_cards,write_gift_cards,read_orders,read_products,write_content,write_online_store_navigation,read_online_store_navigation,read_themes,write_themes"

[auth]
redirect_urls = [ "https://gathering-advanced-multi-implies.trycloudflare.com/shopify/callback" ]

[app_proxy]
prefix = "apps"
subpath = "gift-cards"
url = "https://gathering-advanced-multi-implies.trycloudflare.com/gift-cards"
